In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install pandas


In [ ]:
filename = '/content/drive/Shareddrives/Reddit/month/Dec-2019-no-adult-top-10000-4-dif-subreddits.json'

In [ ]:
import pandas as pd
import json
#read data in chunks of 1 million rows at a time

with open(filename) as f:
    data = pd.DataFrame(json.loads(line) for line in f)


In [ ]:
data.head()

ruscheinskyc  ...                                         madajurado
0  {'Bad_Cop_No_Donut': 2, 'DontFundMe': 2, 'brit...  ...  {'environment': 1, 'ireland': 2, 'lgbt': 1, 'U...

[1 rows x 373282 columns]

In [ ]:
new_data = data.T

In [ ]:
new_data.head()

0
ruscheinskyc      {'Bad_Cop_No_Donut': 2, 'DontFundMe': 2, 'brit...
rockyp32          {'Naruto': 1, 'asktrp': 3, 'Semenretention': 2...
AmInATizzy        {'britishproblems': 9, 'JUSTNOMIL': 5, 'TheSil...
randomblackkiddd  {'unpopularopinion': 27, 'atheism': 7, 'Rateme...
GKrollin          {'Connecticut': 7, 'BikiniBottomTwitter': 2, '...

In [ ]:
n = 2000
list_df = [new_data[i:i+n] for i in range(0,new_data.shape[0],n)]
matrix_df = pd.DataFrame()
"""
n = 1000

rem = new_data.shape[0]%n
for i in range(0,new_data.shape[0],n):
  pd.json_normalize(new_data[i:i+n])
"""

'\nn = 1000\n\nrem = new_data.shape[0]%n\nfor i in range(0,new_data.shape[0],n):\n  pd.json_normalize(new_data[i:i+n])\n'

In [ ]:
for i,chunk in enumerate(list_df):
  print(str(i) + ' chunk done')
  list_df[i]=pd.json_normalize(chunk[0])
  if(i==0):
    break
  

0 chunk done


In [ ]:
#list_df[0].to_csv (r'/content/drive/Shareddrives/Reddit/batch0.csv', index = True, header=True)

In [ ]:
matrix_df = list_df[0]

In [ ]:
print(matrix_df.head)

<bound method NDFrame.head of       Bad_Cop_No_Donut  DontFundMe  ...  Hatfilms  chemhelp
0                  2.0         2.0  ...       NaN       NaN
1                  NaN         NaN  ...       NaN       NaN
2                  NaN         NaN  ...       NaN       NaN
3                  NaN         NaN  ...       NaN       NaN
4                  NaN         NaN  ...       NaN       NaN
...                ...         ...  ...       ...       ...
1995               NaN         NaN  ...       NaN       NaN
1996               NaN         NaN  ...       NaN       NaN
1997               NaN         NaN  ...       NaN       NaN
1998               NaN         NaN  ...       NaN       NaN
1999               NaN         NaN  ...       NaN       NaN

[2000 rows x 5731 columns]>


In [ ]:
import numpy as np

train_index = np.random.random(len(matrix_df)) <= 0.7
train_df = matrix_df[train_index]
test_df = matrix_df[~train_index]

In [ ]:
print(train_df.head())

print(test_df.head())

   Bad_Cop_No_Donut  DontFundMe  ...  Hatfilms  chemhelp
3               NaN         NaN  ...       NaN       NaN
6               NaN         NaN  ...       NaN       NaN
7               NaN         NaN  ...       NaN       NaN
8               NaN         NaN  ...       NaN       NaN
9               NaN         NaN  ...       NaN       NaN

[5 rows x 5731 columns]
   Bad_Cop_No_Donut  DontFundMe  ...  Hatfilms  chemhelp
0               2.0         2.0  ...       NaN       NaN
1               NaN         NaN  ...       NaN       NaN
2               NaN         NaN  ...       NaN       NaN
4               NaN         NaN  ...       NaN       NaN
5               NaN         NaN  ...       NaN       NaN

[5 rows x 5731 columns]


In [ ]:
train_df.fillna(0)
subreddits = train_df.columns
print(subreddits)
train_mat = train_df.to_numpy()
print(train_mat)

Index(['Bad_Cop_No_Donut', 'DontFundMe', 'britishproblems', 'PrequelMemes',
       'politics', 'quityourbullshit', 'Cringetopia', 'freefolk', 'trashy',
       'comedynecromancy',
       ...
       '32dollars', 'catswhotrill', 'PointlessStories', 'Homesteading',
       'youtubetv', 'badassanimals', 'DamnNatureYouScary', 'whatcarshouldIbuy',
       'Hatfilms', 'chemhelp'],
      dtype='object', length=5731)
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [ ]:
prediction_mat = np.ones_like(train_mat)


In [ ]:

user_train_like = []
for u in range(len(train_mat)):
    user_train_like.append(np.where(train_mat[u, :] > 0)[0])

numer = np.matmul(train_mat, train_mat.T)
denom = np.sum(train_mat ** 2, axis=1, keepdims=True) ** 0.5
Cosine = numer / np.matmul(denom, denom.T)

recommendation = []
for u in range(len(train_mat)):
    similarities = Cosine[u, :]
    similarities[u] = -1
    N_idx = np.argpartition(similarities, -5)[-5:]
    N_sim = similarities[N_idx]
    scores = np.sum(N_sim.reshape((-1, 1)) * train_mat[N_idx, :], axis=0) / np.sum(N_sim)
    
    train_like = user_train_like[u]
    scores[train_like] = -9999
    top50_iid = np.argpartition(scores, -5)[-5:]
    top50_iid = top50_iid[np.argsort(scores[top50_iid])[-1::-1]]
    recommendation.append(top50_iid)
recommendation = np.array(recommendation)

In [ ]:
print(recommendation)

[[5730 1914 1915 1913 1911]
 [5730 1915 1916 1914 1912]
 [5730 1915 1916 1914 1912]
 ...
 [5730 1912 1913 1911 1909]
 [5730 1912 1913 1911 1909]
 [5730 1914 1915 1913 1911]]


In [ ]:
#Comments made by the user in question
print(new_data[0][1016])
#Recommendations by subreddit ID
print(recommendation[1016], '\n')

#Prints recommended subreddits by name
for i in recommendation[1016]:
 print(subreddits[i])

{'Random_Acts_Of_Amazon': 27, 'SantasLittleHelpers': 14, 'relationships': 1, 'MakeupAddiction': 3, 'Anticonsumption': 1, 'intermittentfasting': 1, 'happy': 4, 'relationship_advice': 3, 'Assistance': 6, 'Entrepreneur': 1, 'CasualConversation': 1, 'NarcissisticAbuse': 3, 'raisedbyborderlines': 1, 'ZeroWaste': 1, 'addiction': 1, 'Visiblemending': 1, 'RandomActsofCards': 2}
[5730 1919 1920 1918 1916] 

chemhelp
MakeupRehab
Lyft
Boise
homeautomation
